### ISSUE TITLE
Could not run app

### ISSUE THREAD

**Issue by sonysm** [aliumujib/AppStoreiOS11#1]
Could not run app
error import LBTAComponents

**Comment by aliumujib** [comment]
Hello @sonysm, you need to run pod install in terminal while you're in the root folder of the project. I totally forgot to add a "how to use" section to my readme.md file. You'll also need an API key from http://apptweak.io

**Comment by aliumujib** [comment]
@sonysm you should add the API key to the Constants.swift file. I'll edit the readme.md file and close this issue later in the day. Let me know how it goes.

Cheers,
Mujib.

**Comment by aliumujib** [comment]
@sonysm 
git clone https://github.com/aliumujib/AppStoreiOS11
open AppStoreiOS11/AppStoreiOS11.xcworkspace
open terminal cd to the directory and run pod install
open Xcode COMMAND + R
